// Generated by CoffeeScript 1.3.3
(function() {
  var current;

  current = function(page) {
    $("#scroller").load("" + page + ".html");
    $("#tree li").removeClass("current_page");
    if (page === "info") {
      $("#index").closest("li").addClass("current_page");
    } else {
      $("#" + page).closest("li").addClass("current_page");
    }
    return 0;
  };

  $(document).ready(function() {
    current("info");
    $("#index").on("click", function(event) {
      current("info");
      return 0;
    });
    $("#skills").on("click", function(event) {
      current("skills");
      return 0;
    });
    $("#education").on("click", function(event) {
      current("education");
      return 0;
    });
    $("#work").on("click", function(event) {
      current("work");
      return 0;
    });
    $("#contact").on("click", function(event) {
      current("contact");
      return 0;
    });
    return $("#copyleft").on("click", function(event) {
      current("copyleft");
      return 0;
    });
  });

}).call(this);
